yamlname: Docker + ngrok Preview
on: 
  push:
    branches: [ main, master ]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: |
        docker build -t flask-app .
        
    - name: Run Flask app with ngrok
      run: |
        # Installer ngrok
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok
        
        # Lancer l'app Flask en arrière-plan
        docker run -d -p 5000:5000 --name flask-container flask-app
        
        # Lancer ngrok pour exposer le port 5000
        ngrok http 5000 --log=stdout &
        
        # Attendre que ngrok démarre
        sleep 10
        
        # Récupérer l'URL publique
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | grep -o '"public_url":"[^"]*' | grep https | cut -d'"' -f4)
        echo "🌐 Votre application est accessible sur : $NGROK_URL"
        echo "⏰ URL disponible pendant 120 secondes..."
        
        # Garder actif pendant 120 secondes
        sleep 120
        
        echo "⏹️ Preview terminé"
