name: Serveur Flask temporaire avec ngrok

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le repo
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker

      - name: Construire l’image Docker
        run: |
          docker build -t flask-ngrok .

      - name: Lancer le conteneur
        run: |
          docker run --rm flask-ngrok
