name: Serveur Flask Docker + ngrok temporaire

on: [push]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installer Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Lancer le conteneur Flask en arrière-plan
        run: docker run -d -p 5000:5000 --name flask-running flask-app

      - name: Lancer ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"
          ./ngrok http ${{ secrets.PORT }} --region=${{ secrets.NGROK_REGION }} > ngrok.log &
          sleep 5
          curl http://127.0.0.1:4040/api/tunnels > tunnels.json
          cat tunnels.json
          echo "⏳ Attendez 120 secondes pour tester le lien ci-dessus"

      - name: Pause temporaire de 120s
        run: sleep 120
